[WIP] Fix model load time and memory computation
Cornerstone-OnDemand/modelkit pull request #117
Opened 2021-11-14 09:49 UTC by CyrilLeMat

I noticed a model _load_time and _load_memory_increment doesn't include its dependencies info.
It makes sense but I feel that, as we push for composable models, it is more informative to cumulate the model data if all of its dependencies.
@victorbenichoux  what do you think? Is there a specific need to get the model load time and memory without its dependencies?

2021-11-14 17:05 UTC, victorbenichoux commented
I am not sure that this is a good idea, because model dependencies are shared, and this could create the impression that models use up more memory than they do. 

This makes it much harder to actually figure out what the memory footprint of a complete `ModelLibrary` is. `modelkit.Model` objects are reused. If A depends on B, there is no added memory footprint from having C depend on B too. 

I do think, however, that it could make sense to have this information printed in the `describe` method (for example), or maybe in a CLI if needs be, alongside the usual increments.

2021-11-15 08:40 UTC, CyrilLeMat commented
in retrospect, I think my proposal was a bad idea (also, it added a bug where we count several times the load info of dependencies shared by several dependencies)
I changed the design and only affected the describe method
![image](https://user-images.githubusercontent.com/7548748/141749006-e9a2cc8e-9c1f-4b6e-a45c-240b86d17589.png)

2021-11-24 15:13 UTC, antoinejeannot requested changes
Nice idea! I indicated some minor changes before merging

2021-11-24 15:13 UTC, antoinejeannot commented on modelkit/core/model.py
> +        load_time_including_dependencies = (self._load_time or 0) + sum(
No need for brackets within the sum function

2021-11-24 15:13 UTC, antoinejeannot commented on modelkit/core/model.py
> +        ) + sum([x["memory"] or 0 for x in dependencies_load_info.values()])
^ Same

2021-11-24 15:22 UTC, tgenin commented on modelkit/core/model.py
> +        def get_all_dependencies_load_info(my_dict, my_model):
+ self
```
get_all_dependencies_load_info(self) -> Dict[str, Dict[str, float]]: ...
```

2021-11-24 15:33 UTC, antoinejeannot commented on modelkit/core/model.py
> +        def get_all_dependencies_load_info(my_dict, my_model):
Yup, my bad

2021-12-13 07:39 UTC, CyrilLeMat commented
@antoinejeannot @tgenin @victorbenichoux PTAL. 
The last discussion was: is the recursive function a good idea (vs an array implementation)?
pros: it's clearer and more concise
cons: python has a maximum recursion limit (usually 1000), however unlikely to reach here

2022-04-01 10:03 UTC, tgenin commented on modelkit/core/model.py
> +        def get_all_dependencies_load_info(my_dict, my_model):
no need to inner function here. make a real function and... test it :D

2022-04-01 10:03 UTC, tgenin commented on modelkit/core/model.py
> +            x["time"] or 0 for x in dependencies_load_info.values()
1/ maybe set `"time": model_dep._load_time or 0` directly to avoid this
2/ why model_dep._load_time can be 0 ?

2022-04-03 16:33 UTC, CyrilLeMat commented
@tgenin PTAL

2022-04-04 12:00 UTC, merged